name: Publicar Imagen en Docker hub

on:
  push:
    branches: ["main", "feature/vulnerabilidades"]

jobs:
  test-and-security:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest bandit

      - name: Escaneo de seguridad (Bandit)
        run: bandit -r app.py test_app.py -ll

      - name: Ejecutar pruebas pytest
        run: pytest test_app.py -v

  build-and-push:
    needs: test-and-security
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: true
          no-cache: true
          tags: mariana220308/sample-api:v1

      - name: Escanear contenedor con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "mariana220308/sample-api:v1"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          scanners: vuln
          trivyignores: .trivyignore

      - name: Desplegar en servidor cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Clonar el repo si la carpeta no existe
            if [ ! -d ~/ejercicio_docker-audit2-web ]; then
              git clone https://github.com/mariana-22/ejercicio-docker-audit2.git ~/ejercicio_docker-audit2-web
            fi
            # Instalar docker compose plugin si no está disponible
            if ! docker compose version >/dev/null 2>&1; then
              sudo apt-get update && sudo apt-get install -y docker-compose-plugin
            fi
            cd ~/ejercicio_docker-audit2-web
            docker compose pull app-backend
            docker compose up -d